// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTCompanion.API.FantasyFootball.DBContexts;

#nullable disable

namespace TTCompanion.API.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230225200851_initialSeed")]
    partial class initialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AG")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AV")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CanDelete")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ST")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AG = 3,
                            AV = 8,
                            CanDelete = false,
                            Cost = 75000,
                            MA = 7,
                            Name = "Ghoul Runner",
                            PA = 4,
                            RaceId = 1,
                            ST = 3
                        },
                        new
                        {
                            Id = 2,
                            AG = 5,
                            AV = 10,
                            CanDelete = false,
                            Cost = 125000,
                            MA = 3,
                            Name = "Mummy",
                            RaceId = 1,
                            ST = 5
                        });
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfApothecary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfAssistantCoach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfBloodweiserKeg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfBribes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfCheerleader")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfDedicatedFan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfMasterChef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfReRolls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfRiotousRookies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxApothecarys")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAssistantCoachs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBloodweiserKegs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBribes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCheerleaders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDedicatedFans")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMasterChefs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxReRolls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRiotousRookies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 0,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Shambling Undead"
                        },
                        new
                        {
                            Id = 2,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 1,
                            Name = "Snotling"
                        },
                        new
                        {
                            Id = 3,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 4,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Black Orc"
                        },
                        new
                        {
                            Id = 5,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Choas Chosen"
                        },
                        new
                        {
                            Id = 6,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Chaos Dwarf"
                        },
                        new
                        {
                            Id = 7,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Chaos Renegade"
                        },
                        new
                        {
                            Id = 8,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Daemons of Khorne"
                        },
                        new
                        {
                            Id = 9,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Dark Elf"
                        },
                        new
                        {
                            Id = 10,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Dwarf"
                        },
                        new
                        {
                            Id = 11,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Elven Union"
                        },
                        new
                        {
                            Id = 12,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 13,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 100000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Halfling"
                        },
                        new
                        {
                            Id = 14,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "High Elf"
                        },
                        new
                        {
                            Id = 15,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Human"
                        },
                        new
                        {
                            Id = 16,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Imperial Nobility"
                        },
                        new
                        {
                            Id = 17,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Khorne"
                        },
                        new
                        {
                            Id = 18,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Lizardmen"
                        },
                        new
                        {
                            Id = 19,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 0,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Necromantic Horror"
                        },
                        new
                        {
                            Id = 20,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Norse"
                        },
                        new
                        {
                            Id = 21,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 0,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Nurgle"
                        },
                        new
                        {
                            Id = 22,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 1,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = 23,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Old World Alliance"
                        },
                        new
                        {
                            Id = 24,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 25,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Skaven"
                        },
                        new
                        {
                            Id = 26,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Slann"
                        },
                        new
                        {
                            Id = 27,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 1,
                            Name = "Snotling"
                        },
                        new
                        {
                            Id = 29,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 0,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Tomb Kings"
                        },
                        new
                        {
                            Id = 30,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Underworld Denizens"
                        },
                        new
                        {
                            Id = 31,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Vampire"
                        },
                        new
                        {
                            Id = 32,
                            CanDelete = false,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Wood Elf"
                        });
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.SpecialRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("SpecialRules");
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Player", b =>
                {
                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.Race", "Race")
                        .WithMany("Players")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Skill", b =>
                {
                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.Player", "Player")
                        .WithMany("Skills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.SpecialRule", b =>
                {
                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.Race", "Race")
                        .WithMany("SpecialRules")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Player", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Race", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("SpecialRules");
                });
#pragma warning restore 612, 618
        }
    }
}
