// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTCompanion.API.DBContexts;

#nullable disable

namespace TTCompanion.API.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230306155327_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("PlayerRace", b =>
                {
                    b.Property<int>("PlayersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RacesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayersId", "RacesId");

                    b.HasIndex("RacesId");

                    b.ToTable("PlayerRace", (string)null);

                    b.HasData(
                        new
                        {
                            PlayersId = 1,
                            RacesId = 1
                        },
                        new
                        {
                            PlayersId = 2,
                            RacesId = 1
                        });
                });

            modelBuilder.Entity("PlayerSkill", b =>
                {
                    b.Property<int>("PlayersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayersId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("PlayerSkill", (string)null);

                    b.HasData(
                        new
                        {
                            PlayersId = 1,
                            SkillsId = 1
                        });
                });

            modelBuilder.Entity("RaceSpecialRule", b =>
                {
                    b.Property<int>("RacesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpecialRulesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RacesId", "SpecialRulesId");

                    b.HasIndex("SpecialRulesId");

                    b.ToTable("RaceSpecialRule", (string)null);

                    b.HasData(
                        new
                        {
                            RacesId = 1,
                            SpecialRulesId = 1
                        });
                });

            modelBuilder.Entity("TTCompanion.API.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastRequestDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PricePlan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("609e388f-0590-4a06-afb7-db482e7d0f08"),
                            AccessTokens = 1,
                            EmailAddress = "email@email.com",
                            FirstName = "admin",
                            LastName = "user",
                            LastRequestDateTime = new DateTime(2023, 3, 6, 15, 53, 24, 676, DateTimeKind.Local).AddTicks(7655),
                            PasswordHash = "214632487910611991161223601035532169126148",
                            PricePlan = 4,
                            RegistrationDateTime = new DateTime(2023, 3, 6, 15, 53, 24, 676, DateTimeKind.Local).AddTicks(7572),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AG")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AV")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PA")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ST")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AG = 3,
                            AV = 8,
                            Cost = 75000,
                            MA = 7,
                            Name = "Ghoul Runner",
                            PA = 4,
                            ST = 3
                        },
                        new
                        {
                            Id = 2,
                            AG = 5,
                            AV = 10,
                            Cost = 125000,
                            MA = 3,
                            Name = "Mummy",
                            ST = 5
                        });
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfApothecary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfAssistantCoach")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfBloodweiserKeg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfBribes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfCheerleader")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfDedicatedFan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfMasterChef")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfReRolls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostOfRiotousRookies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxApothecarys")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAssistantCoachs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBloodweiserKegs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxBribes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCheerleaders")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDedicatedFans")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMasterChefs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxReRolls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRiotousRookies")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 4,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Black Orc"
                        },
                        new
                        {
                            Id = 5,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Choas Chosen"
                        },
                        new
                        {
                            Id = 6,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Chaos Dwarf"
                        },
                        new
                        {
                            Id = 7,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Chaos Renegade"
                        },
                        new
                        {
                            Id = 8,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Daemons of Khorne"
                        },
                        new
                        {
                            Id = 9,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Dark Elf"
                        },
                        new
                        {
                            Id = 10,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Dwarf"
                        },
                        new
                        {
                            Id = 11,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Elven Union"
                        },
                        new
                        {
                            Id = 12,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = 13,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 100000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Halfling"
                        },
                        new
                        {
                            Id = 14,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "High Elf"
                        },
                        new
                        {
                            Id = 15,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Human"
                        },
                        new
                        {
                            Id = 16,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Imperial Nobility"
                        },
                        new
                        {
                            Id = 17,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Khorne"
                        },
                        new
                        {
                            Id = 18,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Lizardmen"
                        },
                        new
                        {
                            Id = 19,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 0,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Necromantic Horror"
                        },
                        new
                        {
                            Id = 20,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Norse"
                        },
                        new
                        {
                            Id = 21,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 0,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Nurgle"
                        },
                        new
                        {
                            Id = 22,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 1,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = 23,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Old World Alliance"
                        },
                        new
                        {
                            Id = 24,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Orc"
                        },
                        new
                        {
                            Id = 1,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 0,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Shambling Undead"
                        },
                        new
                        {
                            Id = 25,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Skaven"
                        },
                        new
                        {
                            Id = 26,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 50000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Slann"
                        },
                        new
                        {
                            Id = 2,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 1,
                            Name = "Snotling"
                        },
                        new
                        {
                            Id = 27,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 0,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Tomb Kings"
                        },
                        new
                        {
                            Id = 28,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 50000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Underworld Denizens"
                        },
                        new
                        {
                            Id = 29,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 70000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Vampire"
                        },
                        new
                        {
                            Id = 30,
                            CostOfApothecary = 50000,
                            CostOfAssistantCoach = 10000,
                            CostOfBloodweiserKeg = 50000,
                            CostOfBribes = 100000,
                            CostOfCheerleader = 10000,
                            CostOfDedicatedFan = 10000,
                            CostOfMasterChef = 300000,
                            CostOfReRolls = 60000,
                            CostOfRiotousRookies = 100000,
                            MaxApothecarys = 1,
                            MaxAssistantCoachs = 6,
                            MaxBloodweiserKegs = 2,
                            MaxBribes = 3,
                            MaxCheerleaders = 12,
                            MaxDedicatedFans = 6,
                            MaxMasterChefs = 1,
                            MaxReRolls = 8,
                            MaxRiotousRookies = 0,
                            Name = "Wood Elf"
                        });
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Modifiable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Modifiable = false,
                            Name = "Dodge"
                        },
                        new
                        {
                            Id = 2,
                            Modifiable = false,
                            Name = "Defensive"
                        });
                });

            modelBuilder.Entity("TTCompanion.API.FantasyFootball.Entities.SpecialRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Modifiable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpecialRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Modifiable = false,
                            Name = "Masters of Undeath"
                        });
                });

            modelBuilder.Entity("PlayerRace", b =>
                {
                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerSkill", b =>
                {
                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RaceSpecialRule", b =>
                {
                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.Race", null)
                        .WithMany()
                        .HasForeignKey("RacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCompanion.API.FantasyFootball.Entities.SpecialRule", null)
                        .WithMany()
                        .HasForeignKey("SpecialRulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
